/** Prefer WebP sibling for product PNGs (generated by compress script). */
export function displayImageSrc(src: string): string {
  if (!src || !src.startsWith("/")) return src;
  if (/\.png$/i.test(src) && (src.startsWith("/products/") || src.startsWith("/uploads/"))) {
    return src.replace(/\.png$/i, ".webp");
  }
  return src;
}