/** Prefer WebP sibling for large product PNGs (generated by compress script). */
export function displayImageSrc(src: string): string {
  if (!src || !src.startsWith("/")) return src;
  // our-gears cards use small dedicated PNGs — no WebP sibling, keep original
  if (src.startsWith("/products/our-gears/")) return src;
  if (/\.png$/i.test(src) && (src.startsWith("/products/") || src.startsWith("/uploads/"))) {
    return src.replace(/\.png$/i, ".webp");
  }
  return src;
}