/** Prefer WebP sibling for product PNGs (generated by compress script). */
export function displayImageSrc(src: string): string {
  if (!src || !src.startsWith("/")) return src;
  // Our Gears cards — keep authored PNGs (correct art, already small)
  if (src.includes("/our-gears/") && /\.png$/i.test(src)) return src;
  if (/\.png$/i.test(src) && (src.startsWith("/products/") || src.startsWith("/uploads/"))) {
    return src.replace(/\.png$/i, ".webp");
  }
  return src;
}